language: c
compiler: gcc

env:
 - CMAKE_ARGS="-DCMAKE_C_FLAGS=-m32" CMAKE_INCLUDE_PATH=/usr/include/glib-2.0/
 - CMAKE_ARGS=

before_install:
 - sudo apt-add-repository -y ppa:vala-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfuse-dev libglib2.0-dev cmake libc6-dev binutils valac libgee-0.8-dev
 - sudo apt-get install -qq gcc-multilib g++-multilib libc6-dev-i386 libglib2.0-0:i386
 - sudo apt-get build-dep fuse
 - apt-get source fuse
 - cd fuse-*
 - CFLAGS=-m32 ./configure --host=i386-linux-gnu --prefix=/usr
 - make -j 50
 - sudo make install
 - cd -
 - cd ./LibcWrapGenerator
 - valac --pkg gee-0.8 --pkg posix --pkg glib-2.0 --pkg gio-2.0 ./LibcWrapGenerator.vala
 - sudo ./LibcWrapGenerator --target 2.14 --libdir /lib --output libcwrap.h
 - sudo cp ./libcwrap.h /usr/include/
 - cd -

script: 
 - export CC='gcc -U_FORTIFY_SOURCE -include /usr/include/libcwrap.h'
 - cmake . $CMAKE_ARGS && make
 - find . -type f
 - file ./AppImageExtract ./AppRun ./AppImageAssistant ./AppImageMonitor

before_deploy:
  git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: Rtz7d+BKUnBT8D5FoE4XXCvVhRSQVdGK/c5VpI6IYuGhwmtx4RIvK78cICFPZq8k1xJm8yOuCOChX6EyElhUkYh5iPzDI/J7IiqBl+z+/V3aXx6W2PKyYLohZW3z9iomQbX2LQ6vHcZsNqQsjKZ2dW7Ja5Q9cZTFKiokMXsAERo=
  skip_cleanup: true
  file_glob: true
  file: 
   - ./AppImageExtract
   - ./AppRun
   - ./AppImageAssistant
   - ./AppImageMonitor
  on:
    tags: true
    all_branches: true
