language: c
compiler: gcc

services:
 - docker

env:
 - DOCKER_IMAGE=toopher/centos-i386:centos6
 - DOCKER_IMAGE=library/centos:6
 - DOCKER_IMAGE=ryankurte/docker-arm-embedded
 - DOCKER_IMAGE=thewtex/cross-compiler-android-arm
 - DOCKER_IMAGE=firemiles/arm-linux-gcc
 - DOCKER_IMAGE=amardomingo/docker-build-arm
 - DOCKER_IMAGE=sdt4docker/raspberry-pi-cross-compiler
 - DOCKER_IMAGE=philipz/raspberry-pi-crosscompile
 - DOCKER_IMAGE=philipz/rpi-raspbian

script:
 - docker run -i -v "${PWD}:/AppImage" "$DOCKER_IMAGE" /bin/bash -c "/AppImage/build.sh"
 - file ./AppImageExtract ./AppRun ./AppImageAssistant ./AppImageMonitor

before_deploy:
  git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: Rtz7d+BKUnBT8D5FoE4XXCvVhRSQVdGK/c5VpI6IYuGhwmtx4RIvK78cICFPZq8k1xJm8yOuCOChX6EyElhUkYh5iPzDI/J7IiqBl+z+/V3aXx6W2PKyYLohZW3z9iomQbX2LQ6vHcZsNqQsjKZ2dW7Ja5Q9cZTFKiokMXsAERo=
  skip_cleanup: true
  file_glob: true
  file: 
   - ./AppImageExtract
   - ./AppRun
   - ./AppImageAssistant
   - ./AppImageMonitor
  on:
    tags: true
    all_branches: true
